#!/usr/bin/env ruby
require 'pretty_search'

options = begin
            PrettySearch.parse_cli_opts
          rescue GetoptLong::Error
            abort
          end
if options[:help]
  puts PrettySearch::HELP_TEXT
  return
end

query = begin
          PrettySearch.parse_query(ARGV)
        rescue => e
          abort e.message
        end
PrettySearch.run(query, options)
